
// GALLERY -> SCHOOL VIDEO
// VIDEO GALLERY CAN BE ADDED FROM HERE 
export const VideoData = [
    "https://www.youtube.com/embed/C1rDe3DB8v0",
    "https://www.youtube.com/embed/PukZY2tpOXM",
    "https://www.youtube.com/embed/v7934bIiubw",
    "https://www.youtube.com/embed/iQOuV6hfNW8",
    "https://www.youtube.com/embed/ciVviFXLWyg",
    "https://www.youtube.com/embed/aisqjYJ0tkA",
    "https://www.youtube.com/embed/2mDaMbj0f2s",
    "https://www.youtube.com/embed/-80Xv8MEcbI",
    "https://www.youtube.com/embed/_hGeB-xu2aM",
    "https://www.youtube.com/embed/i8lvgkXuMFY",
    "https://www.youtube.com/embed/GfjgwTnwvac",
    "https://www.youtube.com/embed/cCG4qQeIjPA",
    "https://www.youtube.com/embed/2Rnl56KZRYE",
    "https://www.youtube.com/embed/HfgADzq2Ejc",
    
    // ... Add more image URLs here
  ];


  
// GALLERY -> SCHOOL PHOTO
//MAIN GALLERY PHOTOS CAN BE ADDED FROM HERE 
export const PhotosData = [
"https://drive.google.com/uc?export=view&id=1Pvn5H5xq_wcW3cptYt8MSl_DVVRp6cyk",
"https://drive.google.com/uc?export=view&id=1qavBcffeW5_tI7riw_FBj3g5ryZTZGsb",
"https://drive.google.com/uc?export=view&id=10noLzVIoyfAZBFUNiKpGp4jzYLr5ma5L", 
"https://drive.google.com/uc?export=view&id=1BD_oXAarQDC3rEfu02VT_n2p4hvFYtry",
"https://drive.google.com/uc?export=view&id=1V4-WscP9VSejw596ll1C2BiVA15_ezPb",
"https://drive.google.com/uc?export=view&id=11HnX1eaYdVMlOIuSj7E8XGZJ9meyX2FW", 
"https://drive.google.com/uc?export=view&id=1EO1EjaDaHd3QUdnpcyvpLtuUxSk3EfDL", 
"https://drive.google.com/uc?export=view&id=1RV0kurj02ulYjQ05RnTPA3o4MaCMobTc", 
"https://drive.google.com/uc?export=view&id=1gAm_YFM5_X0jlynWr1_MWthqanlARthd", 
"https://drive.google.com/uc?export=view&id=1yx_d2Uz68bTVbC54u0XW1Xh764aVOJth",
"https://drive.google.com/uc?export=view&id=16yxQED9ySe9JzOTIkMaKN3dZHBvKh64s", 
"https://drive.google.com/uc?export=view&id=1FZwSc2tHj2n2wMi72WSYBrLLbrkFWrzI", 
"https://drive.google.com/uc?export=view&id=1O3utu-IzbQTznQpex4FdsrfFaSWvlavC", 
"https://drive.google.com/uc?export=view&id=1PwEfsESaJ8rTtAD-ctY_eAtmd7NmQrqT", 
"https://drive.google.com/uc?export=view&id=1dpwbW6zEm7mFkUv6DgJiqAbYNotA169K", 
"https://drive.google.com/uc?export=view&id=1hICzVQLcsxL3P17909H5y0BlDE_a_vjB", 
"https://drive.google.com/uc?export=view&id=1meIwlT1bDNS71DcYk4ll2xs4QVGvesA0", 
"https://drive.google.com/uc?export=view&id=1piJ_1HP-6M31PwT3HsqsGHYbtq-7YXuY", 
"https://drive.google.com/uc?export=view&id=1to6rwnETG3WATHh7ZXi9p_Qk4mgzUf2D", 
"https://drive.google.com/uc?export=view&id=1zxaMK3rJM9sWA1gnwYr7ElGYaWbKSrjA",
"https://drive.google.com/uc?export=view&id=10nb_EF_cdRvkTEop22sTElQJcwxxuoQT", 
"https://drive.google.com/uc?export=view&id=11JwNstFs0RRNs01NdjMuhW-ZGZlvw2Dm", 
"https://drive.google.com/uc?export=view&id=13X0Q2EyUz9_0iA2Omhuk6YoDqFuwwCTB", 
"https://drive.google.com/uc?export=view&id=1CBlqxiFcM9UKBsuXxhawCKJtacDILkM8", 
"https://drive.google.com/uc?export=view&id=1Hx9BlFjR8SjX7zIiYsgTV8-QL0ttxp3c", 
"https://drive.google.com/uc?export=view&id=1JtSm7JzeyIoumDalXc-38yYifBjj1qXm", 
"https://drive.google.com/uc?export=view&id=1LorsXpAGlDxXtDwfo1CT_o9Xjm018edW", 
"https://drive.google.com/uc?export=view&id=1P8w94bP8cdIRMJie2E6BY95YpEXrYhL9", 
"https://drive.google.com/uc?export=view&id=1QxCKhCGgHg7vBkXW0qwGLqzPk3RoVLoL", 
"https://drive.google.com/uc?export=view&id=1Y99qEV9QTb3aFKuyIUUHRVTmNPpvPM_V", 
"https://drive.google.com/uc?export=view&id=1cuyLUnVojJSPQIXXt90mN-LM7y8a8Dg3", 
"https://drive.google.com/uc?export=view&id=1k5RqghTibFanuG8CYEBUhQxj4zVMDqe9", 
"https://drive.google.com/uc?export=view&id=1zKhfwZTQlk1yXYE5YnjhKOeKSRbpP_mq", 
"https://drive.google.com/uc?export=view&id=1zdMqGEjJ257VW-DOb_TFS9R3lMzM1bnn", 
"https://drive.google.com/uc?export=view&id=1zgpS6dIKGcUwz8MdkKFhW09MY7kJed4s",
"https://drive.google.com/uc?export=view&id=1-4nZgLnyrm48GRLO4PB1gyK63M9uV5kG", 
"https://drive.google.com/uc?export=view&id=10x9bJJjLBgHa_4lIoQzd8EfawNyOFTyH", 
"https://drive.google.com/uc?export=view&id=14E5zmt10mjyabWtm7dL-ZMSuVQKmbcTC", 
"https://drive.google.com/uc?export=view&id=14Ldry4qlXCbNzCWN_WPpdEbKPP73Of6l", 
"https://drive.google.com/uc?export=view&id=14fxxf94JcDoCTDkdRpt5LQ34CpfrPfDp", 
"https://drive.google.com/uc?export=view&id=15FqtqTR0N0qXGU0cfCdpVPnW_EQE07tl", 
"https://drive.google.com/uc?export=view&id=15VM-yPlTW6sAJWDGfRcbaGpFeZafZtO2", 
"https://drive.google.com/uc?export=view&id=19OQwPo0At4FLid_qeK5Qfa-xry-jvTpH", 
"https://drive.google.com/uc?export=view&id=19yU7IJS5XfLNZwc-hOYLf9rgyyCM1UBt", 
"https://drive.google.com/uc?export=view&id=1AMiTH_dw9oHEfucGajezgdbghxXFyB80", 
"https://drive.google.com/uc?export=view&id=1BNKR9OS2-6_Trz5mkmOALODfDDDtk3T0", 
"https://drive.google.com/uc?export=view&id=1C1CSmWRmm51kWxxxayVfrKQIX09udfBk", 
"https://drive.google.com/uc?export=view&id=1CK-zWi7eiX8xawx8o0gsLBUq75gktbjL", 
"https://drive.google.com/uc?export=view&id=1Co4YF7TxL8Pu2PqJewPTYjHBpHqQqN1C", 
"https://drive.google.com/uc?export=view&id=1DdVM7WUkOYKtUkdnL91FfgpsDjB34fco", 
"https://drive.google.com/uc?export=view&id=1Dl5Aag0w2wun2y6CjCD32M8G6-lPc_Ip", 
"https://drive.google.com/uc?export=view&id=1F4HAiyVDdrMOvpAyIh0uHVWXGOV6nB16", 
"https://drive.google.com/uc?export=view&id=1GFANRq55FmbFOuZU4txdVXLqkOsA-cTv", 
"https://drive.google.com/uc?export=view&id=1Hd6P9xQwq8biViDjnvSZ-YY6zUV5vHtv", 
"https://drive.google.com/uc?export=view&id=1K69tj2JRnAzXI868OcVoD9GwbysVd8FZ", 
"https://drive.google.com/uc?export=view&id=1KVCBZC8DvbfvRhxDmS_HTZqoozhPpmSD", 
"https://drive.google.com/uc?export=view&id=1KiS1lurrnXjyBvoGWP4iJJ03AS4Ar55f", 
"https://drive.google.com/uc?export=view&id=1Lx8zB5VKgnRqP8JvSNYSUr4pw6bzniG-", 
"https://drive.google.com/uc?export=view&id=1QDDNwhpjduPfcTDIINClcDMY2GYtQ3hA", 
"https://drive.google.com/uc?export=view&id=1TPGZgaXKo1w3H_K8WeweU9KuSEM_Zomw", 
"https://drive.google.com/uc?export=view&id=1Tw-Zm13D-RP7az9iX2EdUN4lMPltPM2Z", 
"https://drive.google.com/uc?export=view&id=1UpWWBam0RJTU1MW5teUGkGAyYOvdCeRu", 
"https://drive.google.com/uc?export=view&id=1VcgF8r5A4h5lIYTsGW0L2tASYl9UPhtG", 
"https://drive.google.com/uc?export=view&id=1WRRExEVvatQrCqzRsK7cVqfKI0GmzrOS", 
"https://drive.google.com/uc?export=view&id=1WwlIKr1JoVh1jF-RAfNL3mes5RLVCBPW", 
"https://drive.google.com/uc?export=view&id=1dGgYZZfmxGwIUXLo1Cpxjc0FHD-SXBBd", 
"https://drive.google.com/uc?export=view&id=1hzQUkti6pqiIerx0lDHAUcu9YlW0ZtGZ", 
"https://drive.google.com/uc?export=view&id=1i_Ic0B5w3St06Vu_C5jtZS-a4l9f_YVW", 
"https://drive.google.com/uc?export=view&id=1iojU02AonGfln8x0jynQa2UkwghySkQN",
"https://drive.google.com/uc?export=view&id=1oYoOMd5aLRr9fxxThdTGUL4Y6Cc0EP9V", 
"https://drive.google.com/uc?export=view&id=1pDWyn3YQ1RY4_bfuSWvgB94w_tRMhSVK", 
"https://drive.google.com/uc?export=view&id=1qWRe4aGHPnmbvFg26fGz1jh1Gy2JF1_2", 
"https://drive.google.com/uc?export=view&id=1tk8adadnNSdRFrAx7rK1xB3Tr1q0OszZ", 
"https://drive.google.com/uc?export=view&id=1uWyIVZJUm-vjwn9IPAwEmpgMAJDSbf05", 
"https://drive.google.com/uc?export=view&id=1ushmmRgH9tn_h6JZ_D3z31lOJu9Pmgwo", 
"https://drive.google.com/uc?export=view&id=1vfml6giwBC554FAM1fvKsdStha_hu18u", 
"https://drive.google.com/uc?export=view&id=1xuN1ezrOb4k0E2v4R6iHQPPAhVLqKAdt", 
"https://drive.google.com/uc?export=view&id=1z7zzKgpxiFq3Os1m7Sh3lSGItyzinbzy", 
"https://drive.google.com/uc?export=view&id=1zIXjJNOFZW5rzoT1k345fncFLTIU1tps",
"https://drive.google.com/uc?export=view&id=10gYDoErWC2WoDolxxrtdoH6EXdmYT1Gw", 
"https://drive.google.com/uc?export=view&id=12TRUW7trp-zhrOvi7-hXseg1-eV6ODGA", 
"https://drive.google.com/uc?export=view&id=13lt9u4AdhvRCHK6--yOWHmsmlJyZeFYB", 
"https://drive.google.com/uc?export=view&id=15lPe1jL6L9N3W5xs-SUxswA5soNE8J_x", 
"https://drive.google.com/uc?export=view&id=17yjAn_GrOURO8bcJMvn2bPgfTu1Zw1Za", 
"https://drive.google.com/uc?export=view&id=19Ud0GSqR3GIwRbA7iqDrqpuxd-UQNVc7", 
"https://drive.google.com/uc?export=view&id=19o2KLfvFHEMHOzA4h1J_kiK7p9a7fjOM", 
"https://drive.google.com/uc?export=view&id=1GROHdj7Fv6MNUGjWXdtMvJlAPIy8TZU-", 
"https://drive.google.com/uc?export=view&id=1GmVsve6ON_xlfNz_jHb-rTC6jMLYUA5C", 
"https://drive.google.com/uc?export=view&id=1I5XvN4MwCVC05L9dfnNMH4icSUq7-0WL", 
"https://drive.google.com/uc?export=view&id=1JvGdSsrs51Aaixo-5I8nhBk3R39CoJKM", 
"https://drive.google.com/uc?export=view&id=1NN2gGyaeTNJP6b1tdCbk4W49rD9wprmI", 
"https://drive.google.com/uc?export=view&id=1PktnoLY_gK9oyVrXcpLSstCx3t8mMgrO", 
"https://drive.google.com/uc?export=view&id=1RqCNTxd9026bTR45IQyn0AWDjbRu65yj", 
"https://drive.google.com/uc?export=view&id=1S-o_7DBPsbod7eLb6pRGNjru4k6NM6Vm", 
"https://drive.google.com/uc?export=view&id=1S1Hx4FLG1bpaBqBJUVcpXT4csu6I_COu", 
"https://drive.google.com/uc?export=view&id=1SRzBD5v4JcKrwriyLpz_du_d9J4t93Ls", 
"https://drive.google.com/uc?export=view&id=1U1VlDfgnw01ZKDF0cb70HORTv-ur8iLA", 
"https://drive.google.com/uc?export=view&id=1V0iBbD1defttziZL4tyWbU3mJbPOlVUq", 
"https://drive.google.com/uc?export=view&id=1Xv4vYSxtJF1B0SZV2V9gVF4lRkfllfqo", 
"https://drive.google.com/uc?export=view&id=1Y2Q5ziPg--XjX7aH9v1aH8ESfKpM8qJT", 
"https://drive.google.com/uc?export=view&id=1YGMyrsHACCDFXIKcxA5qimGmdprR_qh1", 
"https://drive.google.com/uc?export=view&id=1_111vDPjK-NJzET76s5kvk_Qx7-zdfqn", 
"https://drive.google.com/uc?export=view&id=1_adeRkDWKxLl1LA1CUSx_y5943I90SRT", 
"https://drive.google.com/uc?export=view&id=1c9253tTJ8HN4PiBriWgxv9swbkrmIIZH", 
"https://drive.google.com/uc?export=view&id=1cluRM7v9kQRMV6cOLY9pVzc49CysIQ9I", 
"https://drive.google.com/uc?export=view&id=1dt0pt62uZNvkuXM8gJyVJR0kAU8SEDZ6", 
"https://drive.google.com/uc?export=view&id=1etYq2FzOJPJLHDT9e3B4aSgW-uWaPVYt", 
"https://drive.google.com/uc?export=view&id=1mvyrU2t933QTWsD3XPPUGRCdlvmquSew", 
"https://drive.google.com/uc?export=view&id=1p6-2dg4B6h8xi8rpWHeeggAxWTCG3WLi", 
"https://drive.google.com/uc?export=view&id=1qlAI2kAuZMdVVUv9VkpgPgPg1WCR5b_s", 
"https://drive.google.com/uc?export=view&id=1radp28sSVnWI1o-1zSeikeBOZPaKSxTu", 
"https://drive.google.com/uc?export=view&id=1rdxHXNngCYf2jPKRyojYOIwNeZBbfeMo", 
"https://drive.google.com/uc?export=view&id=1rwf518nhpCPF9eqCI939VMnvVTSsqP5J", 
"https://drive.google.com/uc?export=view&id=1sLQo2FNqVv571XsgR87QAdv1cOi9IU6t", 
"https://drive.google.com/uc?export=view&id=1urCEugM23pw6k24ZYaiKeGfR-6PnuPnh", 
"https://drive.google.com/uc?export=view&id=1vwRNdOlIt9-xivnrLraOgzcJ-gIjDMPx", 
"https://drive.google.com/uc?export=view&id=1xkIaJOXrTGb3eN5FuzYrNMFppzDZ-AnK", 
"https://drive.google.com/uc?export=view&id=1yVnLDrR61hKvYZyvsv6ik6t02tyJcelH", 
"https://drive.google.com/uc?export=view&id=1zfzQLmrTgTao3smAs_TSoYjTNSFcuwDT",
    
    // ... Add more image URLs here
  ];
  

  
// GALLERY -> EVENT PHOTO
//EVENT PHOTOS CAN BE ADDED FROM HERE 
export const EventData = [
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgy0tv-B__tMoaNlAkTTM1pYeuUF0zaJf7FgMZ0a5cmD41xStwa3jKQfXbgmc_KITbdr91lydt21EJAS3dkCyljzAPL_rti6g6zCT602sL9nqgiUksEELM5cST_9Er2k4MX9LhJsTCmJoFr91Gd5oT5YU-X9QaU6Or1mNEZ3WCnCUYspdp28B2kGGvwaC0/s320/Republicday.webp",
    // ... Add more image URLs here
  ];